name: Push the Docker image to EndorLabs Repo
on:
  push:
    branches:
      - main
jobs:
  build-and-scan:
    permissions:
      id-token: write # Write permission is required to request a json web token (JWT) to perform keyless authentication
      packages: write
      contents: read  # Required by actions/checkout@v3 to checkout a private repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Setup with Endor Labs
        uses: endorlabs/github-action/setup@v1
        with:
          namespace: "integration_tests.integration_test2"
          enable_github_action_token: true
          cache-dependency-path: package.json
#      - name: Build Docker
#        run: |
#          docker build -t image:latest .
      - name: Install
        run: |
          npm -v
          npm install
          npm install coa@2.0.2
          npm install nginx@1.0.8
          npm install sshd-core@2.11.0
          npm install jackson-mapper-asl@1.9.13
          npm install package.json
          npm pack
      - name: Use Endorctl
        run: |
          export ENDOR_API_CREDENTIALS_KEY=endr+IV0OYfagvf-7GmJX
          export ENDOR_API_CREDENTIALS_SECRET=endr+SjabT9yPk2THeVJR
          export ENDOR_NAMESPACE=integration_tests.integration_test2
          endorctl api list -r Project --page-size=1
          endorctl scan --include="https://github.com/integrationtests-JFrog/integration-test/blob/main/"
#      - name: Scan with Endor Labs
#        uses: endorlabs/github-action@v1.1.1
#        with:
#          namespace: "integration_tests"
