name: Push the Docker image to EndorLabs Repo
on:
  push:
    branches:
      - main
jobs:
  build-and-scan:
    permissions:
      id-token: write # Write permission is required to request a json web token (JWT) to perform keyless authentication
      packages: write
      contents: read  # Required by actions/checkout@v3 to checkout a private repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Build Docker
        run: docker build -t image:latest .
      - name: Install
        run: |
          npm install
      - name: Setup with Endor Labs
        uses: endorlabs/github-action/setup@v1
        with:
          namespace: "integration_tests/integration_tests2"
          enable_github_action_token: true

      - name: Use Endorctl
        run: |
          export ENDOR_API_CREDENTIALS_KEY=endr+IV0OYfagvf-7GmJX
          export ENDOR_API_CREDENTIALS_SECRET=endr+SjabT9yPk2THeVJR
          export ENDOR_NAMESPACE=integration_tests/integration_tests2
          endorctl api list -r Project --page-size=1
          endorctl scan --include="package.json"
#      - name: Scan with Endor Labs
#        uses: endorlabs/github-action@v1.1.1
#        with:
#          namespace: "integration_tests"
